// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7rfQmBQO7hmcsRu8J738OpLSDdZf6Vpk',
    appId: '1:99569048222:web:e8f3355902cf650148398f',
    messagingSenderId: '99569048222',
    projectId: 'sih-v2-c28b7',
    authDomain: 'sih-v2-c28b7.firebaseapp.com',
    storageBucket: 'sih-v2-c28b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXZv41-q3bBiH-GtB-rNxvUsLNUeJ-o2g',
    appId: '1:99569048222:android:33261d23060cc7db48398f',
    messagingSenderId: '99569048222',
    projectId: 'sih-v2-c28b7',
    storageBucket: 'sih-v2-c28b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_dKIE5MB9cs5KNb8hRK-6mceeQuWp8u4',
    appId: '1:99569048222:ios:d7221db801bb8a8748398f',
    messagingSenderId: '99569048222',
    projectId: 'sih-v2-c28b7',
    storageBucket: 'sih-v2-c28b7.appspot.com',
    iosBundleId: 'com.example.sihV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_dKIE5MB9cs5KNb8hRK-6mceeQuWp8u4',
    appId: '1:99569048222:ios:719797491c417e6448398f',
    messagingSenderId: '99569048222',
    projectId: 'sih-v2-c28b7',
    storageBucket: 'sih-v2-c28b7.appspot.com',
    iosBundleId: 'com.example.sihV2.RunnerTests',
  );
}
